# Generated by Django 3.1.6 on 2021-02-18 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPortal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='resume')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='applications.position')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('RESPOND', 'Respond received'), ('REJECTED', 'Rejected'), ('INVITED', 'Interview invitation received'), ('PASSED', 'Interview passed'), ('FAILED', 'Interview failed'), ('OFFERED', 'Job offer received')], default='APPLIED', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.company')),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='applications.jobportal')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='applications.position')),
            ],
        ),
    ]
